### PR TITLE
 Add pawn.json and a test entry point

### PR DESCRIPTION
**Pull request by Autorojo**
Add sampctl support (pawn.json) and a test entry point which doesn't do much other than contain a call for each function in order to test compilation - see: [Southclaws/sampctl/wiki/Modern-Pawn](https://github.com/Southclaws/sampctl/wiki/Modern-Pawn)

### CODE REVIEW

**Comment by Crayder** [comment]
Why are you changing the groups of those skins? They are cops and medics, your commit removes that information. I'd rather keep that information and you append the new information.

**Comment by Autorojo** [comment]
Hey, @Crayder. The 97718ac commit it's already merged on the repository - see [my previous pull request](https://github.com/Crayder/Skin-Tags/pull/8) and ca7c297. Idk how to remove that commit from this pull request!

**Comment by Crayder** [comment]
Okay sweet! Merging now.

Now... about the skin groups. It's debatable. I use those skins as cops when I use them, but it totally makes sense not to. Tough choice. If the groups were flagged we could use both, but that would be a little much for just a few skins. Though, the main idea of knowing the ped groups is knowing which animations a skin uses and such, those skins do use cop animations. Considering that, it must remain how it currently is or else the information for that ped group would be wrong. Hmm.

**Comment by Crayder** [comment]
Welp, the ped group commit did not reverse. It should be fine. The animation information remains.

**Comment by Autorojo** [comment]
Oh, I understand... 

I am using this include since september 2018 to make work a civil wardrobe on a roleplay server. Something like this:

```PAWN
CMD:wardrobe(playerid, params[])
{
    new skin;

    if(sscanf(params, "d", skin))
        return SendClientMessage(playerid, -1, "USAGE: /wardrobe <skin>");

    if(!IsValidSkin(skin) || skin == 0)
        return SendClientMessage(playerid, -1, "Invalid skin.");

    if((IsFemale(playerid) && GetSkinGender(skin) == SKIN_GENDER_MALE) || (IsMale(playerid) && GetSkinGender(skin) == SKIN_GENDER_FEMALE))
        return SendClientMessage(playerid, -1, "The skin gender must match your character gender.");

    switch(GetSkinGroup(skin))
    {
        case SKIN_GROUP_COP, SKIN_GROUP_MEDIC, SKIN_GROUP_FIREMAN:
            return SendClientMessage(playerid, -1, "You can't use police, medic or fireman uniforms!");
    }

    SetPlayerSkin(playerid, skin);
    SendClientMessage(playerid, -1, "You have modified your dress successfully.");
    return 1;
}
``` 

So, the previous skin groups allow a civil to use police uniforms on a roleplay server. That's why I changed it. But if you consider that the previous skin groups are most accurate than the new ones, it's fine. I will understand, and your include will still beying awesome!

**Pull request merged**
